[package]
name = "mhz19"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[lib]
name = "mhz19"
path = "src/lib.rs"

[[bin]]
name = "log"
path = "src/bin.rs"

[dependencies]
"serial" = "0.4"
err-derive = "0.1"